### PR TITLE
Asthma: Spanish Translations

### PR DESCRIPTION
**Pull request by greinard**
## Overview

This branch finishes adding Spanish language support to the Asthma components.  All translations were created using ChatGPT.  I also added a language toggle to each of the Asthma component stories for easier testing via the Storybook.

The provider report component remains English-only for the time being.  We haven't decided yet whether that should support Spanish as well.

## Security

REMINDER: All file contents are public.

- [x] I have ensured no secure credentials or sensitive information remain in code, metadata, comments, etc.
  - [x] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
  - [x] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [x] These changes do not introduce any security risks, or any such risks have been properly mitigated.

Describe briefly what security risks you considered, why they don't apply, or how they've been mitigated.

- No security risks.  The primary purpose of this PR is to fill in missing translations for previously existing display strings.

### Testing
- [ ] MyDataHelps iOS app
- [ ] MyDataHelps Android app
- [ ] [MyDataHelps website](mydatahelps.org)

### Documentation
- [x] I have added relevant Storybook updates to this PR as well.

### CODE REVIEW

**Comment by ajmenca** [comment]
I've only looked a little bit at some of storybook's underlying setup functionality - but the addition of that language toggle feels like something that we could configure to show up automagically somehow?  Like some of the stuff you did with the dark mode/light mode toggle - this is a pattern we want to better establish for our Stories - but it would be nice if we could do it without having to copy/paste boilerplate.

**Comment by greinard** [comment]
Planning to merge this later today if there are no further objections or requests for delay.  Thanks!

**Review by brandoncharnesky — APPROVED** [review]
Looks good.  MDH-ViewBuilder uses a global switch for language, it would be nice if that could be used in MDH-UI as well at some point.

**Review by reneefromhold — APPROVED** [review]
Echoing the desire for this to be at a higher level. lg otherwise

**Comment by greinard** [comment]
Special thanks to @brandoncharnesky for figuring out a global language picker setup.  I have removed the boilerplate code from each of the stories.

**Pull request merged**
